### ISSUE TITLE
On some pages when using a mobile device a black bar appears on the bottom

### ISSUE THREAD

**Issue by CharisSiarampalis** [aeternity/aescan#247] opened 2023-05-25 11:14 UTC
### Context information

application version: pr-244
device: Samsung Galaxy S22
browser: Chrome 113.0.5672.163, Firefox
operating system: Android

### Steps to reproduce
1.Go to the terms of services page
2.Scroll down the page

### What is expected?
Nothinng should show up
### What is actually happening?
A black bar appears while scrolling sometimes. It disappears when the scrolling is stopped
It also happens on other pages like the token page. But the bar only appears at the edges.

https://github.com/aeternity/aescan/assets/42606212/a4710d3b-74f3-4872-b16a-e4cd3c59c933

**Comment by janmichek** [comment] 2023-05-31 12:13
Suddenly it stopped being an issue. Let's keep it open for a while. If it does not appear, we can close it

**Comment by janmichek** [comment] 2023-06-14 13:00
@CharisSiarampalis Could you help us to check this? I think the issue is not present at any stage now.

**Comment by CharisSiarampalis** [comment] 2023-06-14 13:35
@janmichek I just checked dev and production and i cannot reproduce it. Maybe it was fixed with a pr.

**Comment by janmichek** [comment] 2023-06-14 13:39
@CharisSiarampalis Thank you, closing this

**Closed by janmichek** 2023-06-14 13:39 UTC
Labels: bug
