### ISSUE TITLE
Implement counter for token Holders

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#98] opened 2023-04-17 09:10 UTC
### Please describe the problem that your request should resolve.
When task https://github.com/aeternity/ae_mdw/issues/1257 is released in the MDW we should be able to add pagination information to the token holders table on token details page.

**Comment by janmichek** [comment] 2023-05-30 13:42
Seems to be resolved. Can you help me to confirm @lukeromanowicz ?
If so, please close the issue right away.


https://github.com/aeternity/aescan/assets/15363559/0e8cc3c3-ae55-4b2a-95d2-bf4edb1935ed

**Comment by janmichek** [comment] 2023-05-30 13:45
Aha, I was wrong. I guess its not resolved. The issue is about `counter`, right?

**Comment by lukeromanowicz** [comment] 2023-05-31 12:34
@janmichek correct, it's about the counter above the table :+1:

**Comment by michele-franchi** [comment] 2024-01-11 10:29
@janmichek to check the status of this issue.

**Closed** 2024-09-13 13:54 UTC
Labels: enhancement
