### ISSUE TITLE
Implement automatic sourcemap upload for Sentry 

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#323] opened 2023-06-15 11:52 UTC
### Please describe the problem that your request should resolve.
The error reports we see in Sentry do not use source maps, which results in a stack trace that is very hard to understand. We should make them more readable

### Describe the solution you'd like
Implement automatic source map upload to Sentry - https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite

### Is it already possible to achieve the same outcome in any other way? If so, how?
No, it is not.

**Comment by davidyuk** [comment] 2024-05-11 03:03
duplicate of #252 🙂

**Closed** 2024-05-24 13:58 UTC
Labels: enhancement
