### ISSUE TITLE
Loading indicator of transactions waiting for mdw sync

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#446] opened 2023-08-14 08:50 UTC
When data from mdw is not available we display a lot of placeholders "---" but there's nothing indicating that data will be displayed once mdw is synced.

Example:

<img width="1417" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/522a9463-22b6-4bfa-9fc8-651c7b1acbb1">

**Comment by janmichek** [comment] 2023-08-14 08:55
Yup we need design one more loading concept

**Comment by danilosierrac** [comment] 2023-08-14 10:40
What about "Loading..." as we designed in the skeletons examples? Is the data loading? Is there no data? What is the situation we have to signal the user? That data is coming in moment or there isn't data yet to display?

**Comment by michele-franchi** [comment] 2023-08-16 07:40
@danilosierrac 
It's a concept that could be useful in different places, sometimes we partially load data.

In this case data will come once the middleware completed the sync, usually in a few seconds. We have to tell the user that we are waiting for something because as it is right now it seems data is missing.

**Comment by michele-franchi** [comment] 2023-08-21 10:06
Solution: display a full loader in the panel until mdw has data

**Comment by lukeromanowicz** [comment] 2023-08-23 08:48
Duplicate of #96

**Closed** 2023-08-24 16:05 UTC
Labels: enhancement, design needed
